stages:
  get_processed_data:
    cmd: python ml_pipelines/get_data.py
    deps:
      - ml_pipelines/get_data.py
    outs:
      - data/processed # DVC will now track this entire directory

  train_recommender:
    cmd: python ml_pipelines/train_recommender.py
    deps:
      - data/processed/recommender_features.parquet # Depends on the downloaded file
      - ml_pipelines/train_recommender.py
    outs:
      - models/recommender.pkl
    metrics:
      - reports/metrics.json:
          cache: false

  train_forecaster:
    cmd: python ml_pipelines/train_forecaster.py
    deps:
      - data/processed/forecasting_features.parquet # Depends on the other downloaded file
      - ml_pipelines/train_forecaster.py
    outs:
      - models/forecaster.pkl